import type { VariantPreview } from "./types"

// Static import map — Next.js can statically analyze these for bundling.
// Each entry is a lazy import that resolves to { variants: VariantPreview[] }
export const PREVIEW_REGISTRY: Record<
	string,
	Record<string, () => Promise<{ variants: VariantPreview[] }>>
> = {
	"0.4.0": {
		accordion: () => import("./0.4.0/accordion"),
		"alert-dialog": () => import("./0.4.0/alert-dialog"),
		alert: () => import("./0.4.0/alert"),
		avatar: () => import("./0.4.0/avatar"),
		badge: () => import("./0.4.0/badge"),
		breadcrumbs: () => import("./0.4.0/breadcrumbs"),
		button: () => import("./0.4.0/button"),
		card: () => import("./0.4.0/card"),
		checkbox: () => import("./0.4.0/checkbox"),
		"color-picker": () => import("./0.4.0/color-picker"),
		"date-picker": () => import("./0.4.0/date-picker"),
		"date-range-picker": () => import("./0.4.0/date-range-picker"),
		dialog: () => import("./0.4.0/dialog"),
		divider: () => import("./0.4.0/divider"),
		"dropdown-menu": () => import("./0.4.0/dropdown-menu"),
		"file-details-dialog": () => import("./0.4.0/file-details-dialog"),
		"file-icon": () => import("./0.4.0/file-icon"),
		"file-upload-input": () => import("./0.4.0/file-upload-input"),
		"file-upload": () => import("./0.4.0/file-upload"),
		header: () => import("./0.4.0/header"),
		"image-preview-dialog": () => import("./0.4.0/image-preview-dialog"),
		"number-input": () => import("./0.4.0/number-input"),
		pagination: () => import("./0.4.0/pagination"),
		popover: () => import("./0.4.0/popover"),
		portal: () => import("./0.4.0/portal"),
		progress: () => import("./0.4.0/progress"),
		"radio-group": () => import("./0.4.0/radio-group"),
		radio: () => import("./0.4.0/radio"),
		"rich-text-input": () => import("./0.4.0/rich-text-input"),
		select: () => import("./0.4.0/select"),
		sidebar: () => import("./0.4.0/sidebar"),
		skeleton: () => import("./0.4.0/skeleton"),
		slider: () => import("./0.4.0/slider"),
		spinner: () => import("./0.4.0/spinner"),
		switch: () => import("./0.4.0/switch"),
		tabs: () => import("./0.4.0/tabs"),
		"text-area": () => import("./0.4.0/text-area"),
		"text-input": () => import("./0.4.0/text-input"),
		tooltip: () => import("./0.4.0/tooltip"),
	},
	"0.3.0": {
		accordion: () => import("./0.3.0/accordion"),
		"alert-dialog": () => import("./0.3.0/alert-dialog"),
		alert: () => import("./0.3.0/alert"),
		avatar: () => import("./0.3.0/avatar"),
		badge: () => import("./0.3.0/badge"),
		breadcrumbs: () => import("./0.3.0/breadcrumbs"),
		button: () => import("./0.3.0/button"),
		card: () => import("./0.3.0/card"),
		checkbox: () => import("./0.3.0/checkbox"),
		"color-picker": () => import("./0.3.0/color-picker"),
		"date-picker": () => import("./0.3.0/date-picker"),
		"date-range-picker": () => import("./0.3.0/date-range-picker"),
		dialog: () => import("./0.3.0/dialog"),
		divider: () => import("./0.3.0/divider"),
		"dropdown-menu": () => import("./0.3.0/dropdown-menu"),
		"file-details-dialog": () => import("./0.3.0/file-details-dialog"),
		"file-icon": () => import("./0.3.0/file-icon"),
		"file-upload-input": () => import("./0.3.0/file-upload-input"),
		"file-upload": () => import("./0.3.0/file-upload"),
		header: () => import("./0.3.0/header"),
		"image-preview-dialog": () => import("./0.3.0/image-preview-dialog"),
		"number-input": () => import("./0.3.0/number-input"),
		pagination: () => import("./0.3.0/pagination"),
		popover: () => import("./0.3.0/popover"),
		portal: () => import("./0.3.0/portal"),
		progress: () => import("./0.3.0/progress"),
		"radio-group": () => import("./0.3.0/radio-group"),
		radio: () => import("./0.3.0/radio"),
		"rich-text-input": () => import("./0.3.0/rich-text-input"),
		select: () => import("./0.3.0/select"),
		sidebar: () => import("./0.3.0/sidebar"),
		skeleton: () => import("./0.3.0/skeleton"),
		slider: () => import("./0.3.0/slider"),
		spinner: () => import("./0.3.0/spinner"),
		switch: () => import("./0.3.0/switch"),
		tabs: () => import("./0.3.0/tabs"),
		"text-area": () => import("./0.3.0/text-area"),
		"text-input": () => import("./0.3.0/text-input"),
		tooltip: () => import("./0.3.0/tooltip"),
	},
	"0.2.0": {
		accordion: () => import("./0.2.0/accordion"),
		"alert-dialog": () => import("./0.2.0/alert-dialog"),
		alert: () => import("./0.2.0/alert"),
		avatar: () => import("./0.2.0/avatar"),
		badge: () => import("./0.2.0/badge"),
		breadcrumbs: () => import("./0.2.0/breadcrumbs"),
		button: () => import("./0.2.0/button"),
		card: () => import("./0.2.0/card"),
		checkbox: () => import("./0.2.0/checkbox"),
		"color-picker": () => import("./0.2.0/color-picker"),
		"date-picker": () => import("./0.2.0/date-picker"),
		"date-range-picker": () => import("./0.2.0/date-range-picker"),
		dialog: () => import("./0.2.0/dialog"),
		divider: () => import("./0.2.0/divider"),
		"dropdown-menu": () => import("./0.2.0/dropdown-menu"),
		"file-upload": () => import("./0.2.0/file-upload"),
		"number-input": () => import("./0.2.0/number-input"),
		pagination: () => import("./0.2.0/pagination"),
		popover: () => import("./0.2.0/popover"),
		portal: () => import("./0.2.0/portal"),
		progress: () => import("./0.2.0/progress"),
		"radio-group": () => import("./0.2.0/radio-group"),
		radio: () => import("./0.2.0/radio"),
		"rich-text-input": () => import("./0.2.0/rich-text-input"),
		select: () => import("./0.2.0/select"),
		skeleton: () => import("./0.2.0/skeleton"),
		slider: () => import("./0.2.0/slider"),
		spinner: () => import("./0.2.0/spinner"),
		switch: () => import("./0.2.0/switch"),
		tabs: () => import("./0.2.0/tabs"),
		"text-area": () => import("./0.2.0/text-area"),
		"text-input": () => import("./0.2.0/text-input"),
		tooltip: () => import("./0.2.0/tooltip"),
	},
}
